# Generated by Django 5.2 on 2025-08-02 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocrapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ticket', models.DateField()),
                ('magasin', models.CharField(max_length=200)),
                ('total', models.DecimalField(decimal_places=3, max_digits=10)),
                ('numero_ticket', models.CharField(blank=True, max_length=100, null=True)),
                ('articles_data', models.JSONField(default=list)),
                ('llm_analysis', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccountingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ecriture', models.DateField()),
                ('compte', models.CharField(default='606100', max_length=20)),
                ('description', models.CharField(default='Achat divers', max_length=200)),
                ('libelle_ecriture', models.CharField(max_length=200)),
                ('debit', models.DecimalField(decimal_places=3, max_digits=10)),
                ('credit', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_entries', to='ocrapp.tickethistory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
