# Generated by Django 5.2 on 2025-08-08 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocrapp', '0003_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickethistory',
            name='tva_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='tickethistory',
            name='tva_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
